export const SEARCH_ACTION_TYPES = {
    SET_SEARCH: 'SET_SEARCH',
    SET_SEARCH_MAP: 'SET_SEARCH_MAP',
    SET_ORIENTATION: 'SET_ORIENTATION',
    SET_MORE_PAGE: 'SET_MORE_PAGE',
    SET_PAGE: 'SET_PAGE',
    SET_PER_PAGE: 'SET_PER_PAGE',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_VIEW: 'SET_VIEW',
    SET_CLASS_CHANGE: 'SET_CLASS_CHANGE',
}