export const SEARCH_ACTION_TYPES = {
    SET_SEARCH: 'SET_SEARCH',
    SET_HISTORY: 'SET_HISTORY',
    SET_SHOW_COMMENTS: 'SET_SHOW_COMMENTS',
    SET_WRITE_COMMENTS: 'SET_WRITE_COMMENTS',
    SET_ORIENTATION: 'SET_ORIENTATION',
    SET_PAGE: 'SET_PAGE',
    SET_PER_PAGE: 'SET_PER_PAGE',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_VIEW: 'SET_VIEW',
    SET_CLASS_CHANGE: 'SET_CLASS_CHANGE',
}