export const MODALS_ACTION_TYPES = {
    SET_PHOTO: 'SET_PHOTO',
    SET_PHOTO_ID: 'SET_PHOTO_ID',
    SET_POST: 'SET_POST',
    SET_POST_ID: 'SET_POST_ID',
    SET_POST_MAP: 'SET_POST_MAP',
    SET_PHOTO_MAP: 'SET_PHOTO_MAP',
    SET_AUTHORIZATION: 'SET_AUTHORIZATION',
    SET_CREATE_POST: 'SET_CREATE_POST',
    SET_ZOOM: 'SET_ZOOM',
    SET_FULL_POST: 'SET_FULL_POST',
}