export const BLOG_ACTION_TYPES = {
    SET_POSTS: 'SET_POSTS',
    SET_POSTS_MAP: 'SET_POSTS_MAP',
    SET_POSTS_TITLE: 'SET_POSTS_TITLE',
    SET_POSTS_SUBTITLE: 'SET_POSTS_SUBTITLE',
    SET_POSTS_IMG: 'SET_POSTS_IMG',
    SET_POSTS_TEXT: 'SET_POSTS_TEXT',
    SET_POSTS_ID: 'SET_POSTS_ID',
    SET_MODAL: 'SET_MODAL',
    SET_BLOG_PAGE: 'SET_BLOG_PAGE',
    SET_BLOG_MORE_PAGE: 'SET_BLOG_MORE_PAGE',
    SET_BLOG_SORTED: 'SET_BLOG_SORTED'
}